'use strict';

// Mail accounts are kept behind this service. Provider adapters are injected so
// tests never contact a real mailbox and workers can run the same sync code.
const crypto = require('node:crypto');
const https = require('node:https');
const path = require('node:path');
const { spawn } = require('node:child_process');

const PROVIDERS = [
  { id: 'outlook', name: 'Outlook', label: 'Outlook', authModes: ['oauth'], authMode: 'oauth', domains: ['outlook.com', 'hotmail.com', 'live.com', 'msn.com'], supportsSend: true },
  { id: 'gmail', name: 'Gmail', label: 'Gmail', authModes: ['oauth'], authMode: 'oauth', domains: ['gmail.com', 'googlemail.com'], supportsSend: true },
  { id: 'qq', name: 'QQ 邮箱', label: 'QQ 邮箱', authModes: ['authorization_code'], authMode: 'authorization_code', domains: ['qq.com', 'foxmail.com', 'vip.qq.com'], imapHost: 'imap.qq.com', imapPort: 993, smtpHost: 'smtp.qq.com', smtpPort: 465, supportsSend: false },
  { id: '163', name: '网易邮箱', label: '网易 163', authModes: ['authorization_code'], authMode: 'authorization_code', domains: ['163.com', 'vip.163.com'], imapHost: 'imap.163.com', imapPort: 993, smtpHost: 'smtp.163.com', smtpPort: 465, supportsSend: false },
  { id: '126', name: '网易邮箱', label: '网易 126', authModes: ['authorization_code'], authMode: 'authorization_code', domains: ['126.com'], imapHost: 'imap.126.com', imapPort: 993, smtpHost: 'smtp.126.com', smtpPort: 465, supportsSend: false },
  { id: 'icloud', name: 'iCloud', label: 'iCloud', authModes: ['app_password'], authMode: 'app_password', domains: ['icloud.com', 'me.com', 'mac.com'], imapHost: 'imap.mail.me.com', imapPort: 993, smtpHost: 'smtp.mail.me.com', smtpPort: 587, supportsSend: false },
  { id: 'imap', name: '其他邮箱', label: '其他邮箱', authModes: ['password_or_code'], authMode: 'password_or_code', supportsSend: false },
];
const PROVIDER_IDS = new Set(PROVIDERS.map((item) => item.id));
const OAUTH_PROVIDERS = new Set(['outlook', 'gmail']);
const IMAP_PROVIDERS = new Set(['qq', '163', '126', 'icloud', 'imap']);
const oauthStates = new Map();
const text = (value, max = 500) => { if (value == null) return null; const result = String(value).trim(); return result ? result.slice(0, max) : null; };
const error = (message, code = 'MAIL_REQUEST_INVALID', status = 400) => Object.assign(new Error(message), { code, status });
const hasField = (prisma, model, field) => { try { return Boolean(prisma?._runtimeDataModel?.models?.[model]?.fields?.some((item) => item.name === field)); } catch { return false; } };
const credentialKey = () => { const configured = process.env.MAIL_CREDENTIAL_KEY; if (!configured) throw error('未配置 MAIL_CREDENTIAL_KEY，无法保存邮箱凭据', 'MAIL_CREDENTIAL_KEY_REQUIRED', 503); return crypto.createHash('sha256').update(configured).digest(); };
const encryptCredential = (value) => { if (!value) return null; const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', credentialKey(), iv); const ciphertext = Buffer.concat([cipher.update(String(value), 'utf8'), cipher.final()]); return { credentialCiphertext: ciphertext.toString('base64'), credentialIv: iv.toString('base64'), credentialTag: cipher.getAuthTag().toString('base64') }; };
const decryptCredential = (row) => { if (!row?.credentialCiphertext || !row.credentialIv || !row.credentialTag) return null; const decipher = crypto.createDecipheriv('aes-256-gcm', credentialKey(), Buffer.from(row.credentialIv, 'base64')); decipher.setAuthTag(Buffer.from(row.credentialTag, 'base64')); return Buffer.concat([decipher.update(Buffer.from(row.credentialCiphertext, 'base64')), decipher.final()]).toString('utf8'); };
const accountView = (row) => row && ({ id: row.id, provider: row.provider, email: row.email, displayName: row.displayName, authType: row.authType, status: row.status || (row.authType === 'disconnected' ? 'disconnected' : 'connected'), lastSyncedAt: row.lastSyncedAt, createdAt: row.createdAt, updatedAt: row.updatedAt });
const messageView = (row, includeBody = false) => { if (!row) return null; const output = { ...row }; if (!includeBody) delete output.bodyText; if (row.mailAccount) output.account = row.mailAccount; return output; };
const parseRange = (value) => { const rangeDays = Number(value); if (!Number.isInteger(rangeDays) || ![1, 3, 7, 14, 30, 90, 180].includes(rangeDays)) throw error('rangeDays 必须为 1、3、7、14、30、90 或 180'); return rangeDays; };
const parseDate = (value) => { if (!value) return null; const date = value instanceof Date ? value : new Date(value); if (Number.isNaN(date.getTime())) throw error('日期格式无效', 'INVALID_DATE'); return date; };
const encodeCursor = (row) => Buffer.from(JSON.stringify({ id: row.id, receivedAt: row.receivedAt.toISOString() })).toString('base64url');
function oauthConfig(provider) { if (provider === 'outlook') return { authorize: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize', token: 'https://login.microsoftonline.com/common/oauth2/v2.0/token', profile: 'https://graph.microsoft.com/v1.0/me?$select=mail,userPrincipalName,displayName', clientId: process.env.MAIL_OUTLOOK_CLIENT_ID || process.env.OUTLOOK_CLIENT_ID || process.env.AUTOFILL_OUTLOOK_CLIENT_ID || '', clientSecret: process.env.MAIL_OUTLOOK_CLIENT_SECRET || process.env.OUTLOOK_CLIENT_SECRET || process.env.AUTOFILL_OUTLOOK_CLIENT_SECRET || '', scopes: ['openid', 'email', 'offline_access', 'User.Read', 'Mail.Read', 'Mail.Send'] }; return { authorize: 'https://accounts.google.com/o/oauth2/v2/auth', token: 'https://oauth2.googleapis.com/token', profile: 'https://gmail.googleapis.com/gmail/v1/users/me/profile', clientId: process.env.MAIL_GMAIL_CLIENT_ID || process.env.GMAIL_CLIENT_ID || process.env.AUTOFILL_GMAIL_CLIENT_ID || '', clientSecret: process.env.MAIL_GMAIL_CLIENT_SECRET || process.env.GMAIL_CLIENT_SECRET || process.env.AUTOFILL_GMAIL_CLIENT_SECRET || '', scopes: ['openid', 'email', 'offline_access', 'https://www.googleapis.com/auth/gmail.readonly', 'https://www.googleapis.com/auth/gmail.send'] }; }
function redirectUri(provider) { const base = (process.env.MAIL_OAUTH_CALLBACK_BASE_URL || process.env.APP_URL || 'http://localhost:3001').replace(/\/$/, ''); return `${base}/mail-accounts/oauth/callback?provider=${encodeURIComponent(provider)}`; }
function requestJson(urlString, { method = 'GET', headers = {}, fields = null, timeout = 30000 } = {}, request = https.request) { return new Promise((resolve, reject) => { const target = new URL(urlString); let payload = null; if (fields) { payload = new URLSearchParams(fields).toString(); headers = { ...headers, 'content-type': 'application/x-www-form-urlencoded', 'content-length': Buffer.byteLength(payload) }; } const req = request({ hostname: target.hostname, port: target.port || 443, path: target.pathname + target.search, method, headers }, (res) => { let raw = ''; res.setEncoding('utf8'); res.on('data', (chunk) => { raw += chunk; }); res.on('end', () => { let value; try { value = raw ? JSON.parse(raw) : {}; } catch { return reject(error('邮件服务返回了无效响应', 'MAIL_PROVIDER_INVALID_RESPONSE', 502)); } if (res.statusCode >= 400) return reject(error(value.error_description || value.error?.message || value.error || `邮件服务 HTTP ${res.statusCode}`, 'MAIL_PROVIDER_ERROR', res.statusCode === 429 ? 429 : (res.statusCode === 401 ? 401 : 502))); resolve(value); }); }); req.on('error', reject); req.setTimeout(timeout, () => req.destroy(error('邮件服务请求超时', 'MAIL_PROVIDER_TIMEOUT', 504))); if (payload) req.write(payload); req.end(); }); }

function runPythonProbe(input) {
  return new Promise((resolve, reject) => {
    const child = spawn(process.env.PYTHON_BIN || 'python3', [path.join(__dirname, 'probe.py')], { stdio: ['pipe', 'pipe', 'pipe'] });
    let out = '', err = '';
    child.stdout.on('data', (chunk) => { out += chunk; }); child.stderr.on('data', (chunk) => { err += chunk; });
    child.on('error', reject); child.on('close', (code) => { let result; try { result = JSON.parse(out); } catch { return reject(error('邮箱同步返回了无效结果', 'IMAP_INVALID_RESPONSE', 502)); } if (code !== 0 || result.error) return reject(error(result.error || err || '邮箱连接失败', 'IMAP_CONNECTION_FAILED', 502)); resolve(result); });
    child.stdin.end(JSON.stringify(input));
  });
}

function createMailService({ prisma, adapters = {}, enqueueSync = null, onMessage = null, applicationService = null } = {}) {
  if (!prisma) throw new Error('mail service requires prisma');
  const httpRequest = adapters.request || ((url, options) => requestJson(url, options)); const imapAdapter = adapters.imap || null; const now = adapters.now || (() => new Date()); const pythonProbe = adapters.pythonProbe || runPythonProbe;
  const accountById = (userId, id) => prisma.mailAccount.findFirst({ where: { id: String(id), userId } }); const provider = (id) => PROVIDERS.find((item) => item.id === String(id).toLowerCase());
  const providerByEmail = (email) => { const domain = String(email || '').toLowerCase().split('@')[1]; return PROVIDERS.find((item) => item.domains?.includes(domain)); };
  const accountData = (data) => { if (hasField(prisma, 'MailAccount', 'status')) data.status = data.status || 'connected'; return data; };
  async function providers() { return { items: PROVIDERS.map((item) => ({ ...item, available: item.authMode !== 'oauth' || Boolean(oauthConfig(item.id).clientId), reason: item.authMode === 'oauth' && !oauthConfig(item.id).clientId ? 'OAuth Client ID 未配置' : null })) }; }
  async function listAccounts(userId) { const rows = await prisma.mailAccount.findMany({ where: { userId }, orderBy: { updatedAt: 'desc' } }); return { items: rows.map(accountView).filter((item) => item.status !== 'disconnected') }; }
  async function probeImap(selected, email, secret, options) { if (imapAdapter?.connect) return imapAdapter.connect({ provider: selected, email, secret, ...options }); if (pythonProbe) return pythonProbe({ provider: selected, email, secret, ...options }); if (process.env.NODE_ENV === 'test') return { messages: [] }; throw error('IMAP 适配器尚未配置', 'IMAP_ADAPTER_NOT_CONFIGURED', 503); }
  async function createImap(userId, input = {}) { const selected = provider(input.provider) || providerByEmail(input.email); if (!selected || !IMAP_PROVIDERS.has(selected.id)) throw error('请选择支持 IMAP 的邮箱服务商'); const email = text(input.email, 320)?.toLowerCase(); if (!email || !/^\S+@\S+\.\S+$/.test(email)) throw error('请输入有效邮箱'); const secret = text(input.authorizationCode || input.passwordOrCode || input.password, 1000); if (!secret) throw error(selected.authMode === 'app_password' ? '请输入应用专用密码' : selected.authMode === 'authorization_code' ? '请输入邮箱授权码' : '请输入邮箱密码或授权码'); const probe = await probeImap(selected, email, secret, { rangeDays: 1, verifySmtp: true }); const encrypted = encryptCredential(secret); const data = accountData({ displayName: text(input.displayName, 160), authType: selected.authMode, ...encrypted }); const account = await prisma.mailAccount.upsert({ where: { userId_provider_email: { userId, provider: selected.id, email } }, create: { userId, provider: selected.id, email, ...data }, update: data }); if (probe?.messages?.length) await persistMessages(userId, account, probe.messages, { triggerClassification: false }); return { ...accountView(account), messageCount: probe?.messages?.length || 0 }; }
  async function createOAuthStart(userId, input = {}) { const id = String(input.provider || '').toLowerCase(); if (!OAUTH_PROVIDERS.has(id)) throw error('该邮箱暂不支持 OAuth', 'OAUTH_PROVIDER_UNSUPPORTED'); const config = oauthConfig(id); if (!config.clientId) throw error(`${id === 'outlook' ? 'Outlook' : 'Gmail'} OAuth Client ID 尚未配置`, 'OAUTH_NOT_CONFIGURED', 503); const state = crypto.randomBytes(32).toString('base64url'); const verifier = crypto.randomBytes(48).toString('base64url'); const challenge = crypto.createHash('sha256').update(verifier).digest('base64url'); oauthStates.set(state, { userId, provider: id, verifier, expiresAt: Date.now() + 10 * 60 * 1000 }); const params = new URLSearchParams({ client_id: config.clientId, redirect_uri: redirectUri(id), response_type: 'code', scope: config.scopes.join(' '), state, code_challenge: challenge, code_challenge_method: 'S256', response_mode: 'query', access_type: 'offline', prompt: 'consent' }); return { provider: id, state, authorizationUrl: `${config.authorize}?${params}`, url: `${config.authorize}?${params}` }; }
  async function completeOAuth(userId, input = {}) { const state = String(input.state || ''); const pending = oauthStates.get(state); if (!pending || pending.userId !== userId || pending.expiresAt < Date.now()) throw error('OAuth 状态无效或已过期', 'OAUTH_STATE_INVALID', 400); oauthStates.delete(state); const config = oauthConfig(pending.provider); const token = await httpRequest(config.token, { method: 'POST', fields: { client_id: config.clientId, client_secret: config.clientSecret, code: String(input.code || ''), redirect_uri: redirectUri(pending.provider), grant_type: 'authorization_code', code_verifier: pending.verifier } }); const profile = await httpRequest(config.profile, { headers: { authorization: `Bearer ${token.access_token}` } }); const email = pending.provider === 'outlook' ? (profile.mail || profile.userPrincipalName) : profile.emailAddress; if (!email) throw error('授权成功但未读取到邮箱地址', 'OAUTH_PROFILE_INVALID', 502); const encrypted = encryptCredential(JSON.stringify(token)); const data = accountData({ displayName: text(profile.displayName, 160), authType: 'oauth', ...encrypted }); const account = await prisma.mailAccount.upsert({ where: { userId_provider_email: { userId, provider: pending.provider, email: String(email).toLowerCase() } }, create: { userId, provider: pending.provider, email: String(email).toLowerCase(), ...data }, update: data }); return accountView(account); }
  async function removeAccount(userId, id) { const account = await accountById(userId, id); if (!account) throw error('邮箱账号不存在', 'MAIL_ACCOUNT_NOT_FOUND', 404); const patch = { authType: 'disconnected', credentialCiphertext: null, credentialIv: null, credentialTag: null }; if (hasField(prisma, 'MailAccount', 'status')) patch.status = 'disconnected'; if (hasField(prisma, 'MailAccount', 'disconnectedAt')) patch.disconnectedAt = now(); await prisma.mailAccount.update({ where: { id: account.id }, data: patch }); return { ok: true }; }
  async function startSync(userId, id, input = {}) { const account = await accountById(userId, id); if (!account || account.authType === 'disconnected') throw error('邮箱账号不存在或已断开', 'MAIL_ACCOUNT_NOT_FOUND', 404); const rangeDays = parseRange(input.rangeDays || 7); const idempotencyKey = text(input.idempotencyKey, 200) || `sync:${account.id}:${rangeDays}:${new Date().toISOString().slice(0, 10)}`; const existing = await prisma.syncRun.findUnique({ where: { userId_idempotencyKey: { userId, idempotencyKey } } }); if (existing) return existing; const payload = { userId, mailAccountId: account.id, rangeDays, idempotencyKey, status: 'queued' }; if (hasField(prisma, 'SyncRun', 'startDate')) payload.startDate = parseDate(input.startDate); if (hasField(prisma, 'SyncRun', 'endDate')) payload.endDate = parseDate(input.endDate); const run = await prisma.syncRun.create({ data: payload }); if (enqueueSync) await enqueueSync(run.id); else setImmediate(() => processSync(run.id).catch(() => {})); return run; }
  async function recoverSyncRuns({ staleAfterMs = 15 * 60 * 1000 } = {}) { const cutoff = new Date(Date.now() - staleAfterMs); const where = { OR: [{ status: 'queued' }, { status: 'running', startedAt: { lt: cutoff } }] }; const runs = await prisma.syncRun.findMany({ where, take: 100, orderBy: { createdAt: 'asc' } }); for (const run of runs) { if (enqueueSync) await enqueueSync(run.id); else setImmediate(() => processSync(run.id).catch(() => {})); } return { count: runs.length, runIds: runs.map((run) => run.id) }; }
  async function getSyncRun(userId, id) { const run = await prisma.syncRun.findFirst({ where: { id: String(id), userId } }); if (!run) throw error('同步任务不存在', 'SYNC_RUN_NOT_FOUND', 404); return run; }
  async function listMessages(userId, query = {}) { const limit = Math.min(Math.max(Number(query.limit) || 25, 1), 100); const where = { userId }; if (query.accountId) where.mailAccountId = String(query.accountId); if (query.classification === 'job' || query.classification === 'recruitment') where.isJobRelated = true; if (query.classification === 'other' || query.classification === 'non_recruitment') where.isJobRelated = false; if (query.q) { const q = String(query.q).trim(); if (q) where.OR = [{ subject: { contains: q, mode: 'insensitive' } }, { fromEmail: { contains: q, mode: 'insensitive' } }, { fromName: { contains: q, mode: 'insensitive' } }]; } const from = parseDate(query.from); const to = parseDate(query.to); if (from || to) where.receivedAt = { ...(from ? { gte: from } : {}), ...(to ? { lte: to } : {}) }; if (query.cursor) { let cursor; try { cursor = JSON.parse(Buffer.from(String(query.cursor), 'base64url').toString('utf8')); } catch { throw error('cursor 无效', 'INVALID_CURSOR'); } const at = parseDate(cursor.receivedAt); if (!cursor.id || !at) throw error('cursor 无效', 'INVALID_CURSOR'); where.AND = [{ OR: [{ receivedAt: { lt: at } }, { receivedAt: at, id: { lt: String(cursor.id) } }] }]; } const rows = await prisma.mailMessage.findMany({ where, orderBy: [{ receivedAt: 'desc' }, { id: 'desc' }], take: limit + 1, include: { mailAccount: { select: { provider: true, email: true } } } }); const hasMore = rows.length > limit; return { items: rows.slice(0, limit).map((row) => messageView(row)), nextCursor: hasMore ? encodeCursor(rows[limit - 1]) : null }; }
  async function getMessage(userId, id) { const row = await prisma.mailMessage.findFirst({ where: { id: String(id), userId }, include: { mailAccount: { select: { provider: true, email: true } } } }); if (!row) throw error('邮件不存在', 'MAIL_MESSAGE_NOT_FOUND', 404); return messageView(row, true); }
  async function updateMessage(userId, id, input = {}) { const data = {}; if (input.isJobRelated !== undefined) { if (typeof input.isJobRelated !== 'boolean') throw error('isJobRelated 必须是布尔值'); data.isJobRelated = input.isJobRelated; data.classificationSource = 'manual'; } if (input.applicationId !== undefined) { if (input.applicationId) { const application = await prisma.application.findFirst({ where: { id: String(input.applicationId), userId } }); if (!application) throw error('投递记录不存在', 'APPLICATION_NOT_FOUND', 404); data.applicationId = application.id; } else data.applicationId = null; } if (!Object.keys(data).length) throw error('没有可更新的字段'); const result = await prisma.mailMessage.updateMany({ where: { id: String(id), userId }, data }); if (!result.count) throw error('邮件不存在', 'MAIL_MESSAGE_NOT_FOUND', 404); return messageView(await prisma.mailMessage.findFirst({ where: { id: String(id), userId } })); }
  function safeAnalysis(input = {}) {
    const source = input && typeof input === 'object' && input.result && typeof input.result === 'object' ? input.result : input;
    const output = {};
    const textFields = ['company', 'title', 'role', 'status', 'contact', 'location', 'summary', 'jobUrl', 'assessmentUrl', 'interviewUrl'];
    for (const field of textFields) if (source[field] !== undefined && source[field] !== null) output[field] = text(source[field], field === 'summary' ? 4000 : 1000);
    for (const field of ['appliedOn', 'eventStart', 'eventEnd']) if (source[field]) {
      const parsed = parseDate(source[field]);
      output[field] = parsed.toISOString();
    }
    for (const field of ['jobUrl', 'assessmentUrl', 'interviewUrl']) if (output[field]) {
      try { const parsed = new URL(output[field]); if (!['http:', 'https:'].includes(parsed.protocol)) output[field] = null; }
      catch { output[field] = null; }
    }
    if (output.status && !new Set(['saved', 'applied', 'screening', 'interview', 'offer', 'closed']).has(output.status)) output.status = 'saved';
    output.isJobRelated = source.isJobRelated !== false;
    return output;
  }
  async function updateAnalysis(userId, id, input = {}) {
    const existing = await prisma.mailMessage.findFirst({ where: { id: String(id), userId } });
    if (!existing) throw error('邮件不存在', 'MAIL_MESSAGE_NOT_FOUND', 404);
    const result = safeAnalysis(input);
    const data = { aiResult: result, isJobRelated: result.isJobRelated, classificationSource: 'manual', classificationVersion: 'manual-v1', classificationReason: '用户确认的邮件解析结果' };
    if (result.isJobRelated && applicationService && result.company && (result.title || result.role)) {
      const application = await applicationService.upsertFromMail(userId, id, result);
      if (application) data.applicationId = application.id;
    }
    await prisma.mailMessage.update({ where: { id: String(id) }, data });
    return { message: messageView(await prisma.mailMessage.findFirst({ where: { id: String(id), userId }, include: { mailAccount: { select: { provider: true, email: true } } } }), true), application: data.applicationId ? await prisma.application.findFirst({ where: { id: data.applicationId, userId } }) : undefined };
  }
  async function persistMessages(userId, account, messages, { triggerClassification = true } = {}) { const stored = []; for (const item of messages || []) { const providerMessageId = text(item.providerMessageId || item.messageId, 500); if (!providerMessageId) continue; const data = { userId, mailAccountId: account.id, providerMessageId, threadId: text(item.threadId, 500), fromName: text(item.fromName || item.sender, 320), fromEmail: text(item.fromEmail, 320), subject: text(item.subject, 1000) || '(无主题)', snippet: text(item.snippet, 1000), bodyText: item.body == null && item.bodyText == null ? null : String(item.body ?? item.bodyText).trim(), receivedAt: parseDate(item.receivedAt) || now() }; const row = await prisma.mailMessage.upsert({ where: { mailAccountId_providerMessageId: { mailAccountId: account.id, providerMessageId } }, create: data, update: data }); stored.push(row); if (triggerClassification && onMessage) { try { await onMessage(row); } catch { /* one message classification must not fail the sync run */ } } } return stored; }
  async function processSync(runId) { const run = await prisma.syncRun.findUnique({ where: { id: String(runId) } }); if (!run) throw error('同步任务不存在', 'SYNC_RUN_NOT_FOUND', 404); const account = await prisma.mailAccount.findUnique({ where: { id: run.mailAccountId } }); if (!account) throw error('邮箱账号不存在', 'MAIL_ACCOUNT_NOT_FOUND', 404); await prisma.syncRun.update({ where: { id: run.id }, data: { status: 'running', startedAt: now() } }); try { const secret = decryptCredential(account); if (!secret) throw error('邮箱凭据已失效，请重新登录', 'MAIL_CREDENTIAL_MISSING', 401); let messages = []; if (account.authType === 'oauth') { let token = JSON.parse(secret); try { messages = await fetchOAuthMessages(account.provider, token, run.rangeDays, httpRequest); } catch (caught) { if (caught.status !== 401 || !token.refresh_token) throw caught; const config = oauthConfig(account.provider); const refreshed = await httpRequest(config.token, { method: 'POST', fields: { client_id: config.clientId, client_secret: config.clientSecret, refresh_token: token.refresh_token, grant_type: 'refresh_token' } }); token = { ...token, ...refreshed }; const refreshedData = { ...encryptCredential(JSON.stringify(token)) }; await prisma.mailAccount.update({ where: { id: account.id }, data: refreshedData }); messages = await fetchOAuthMessages(account.provider, token, run.rangeDays, httpRequest); } } else { const selected = provider(account.provider); const result = await probeImap(selected, account.email, secret, { rangeDays: run.rangeDays, verifySmtp: false }); messages = result?.messages || []; } const stored = await persistMessages(run.userId, account, messages); const patch = { status: 'succeeded', completedAt: now() }; if (hasField(prisma, 'SyncRun', 'processedCount')) patch.processedCount = stored.length; if (hasField(prisma, 'SyncRun', 'failedCount')) patch.failedCount = Math.max(0, messages.length - stored.length); await prisma.mailAccount.update({ where: { id: account.id }, data: { lastSyncedAt: now() } }); return prisma.syncRun.update({ where: { id: run.id }, data: patch }); } catch (caught) { const patch = { status: 'failed', completedAt: now(), error: text(caught.message, 1000) }; if (hasField(prisma, 'SyncRun', 'errorMessage')) { delete patch.error; patch.errorMessage = text(caught.message, 1000); } await prisma.syncRun.update({ where: { id: run.id }, data: patch }); throw caught; } }
  return { providers, listAccounts, createImap, createOAuthStart, completeOAuth, removeAccount, startSync, processSync, recoverSyncRuns, getSyncRun, listMessages, getMessage, updateMessage, updateAnalysis, persistMessages, accountView };
}
async function fetchOAuthMessages(provider, token, rangeDays, request) { const since = new Date(Date.now() - Number(rangeDays) * 86400000).toISOString(); if (provider === 'outlook') { let next = `https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$top=100&$orderby=receivedDateTime desc&$filter=${encodeURIComponent(`receivedDateTime ge ${since}`)}&$select=id,subject,from,receivedDateTime,internetMessageId,conversationId,bodyPreview,body`; const rows = []; while (next && rows.length < 500) { const page = await request(next, { headers: { authorization: `Bearer ${token.access_token}` } }); rows.push(...(page.value || [])); next = page['@odata.nextLink'] || null; } return rows.map((item) => ({ providerMessageId: item.internetMessageId || item.id, threadId: item.conversationId, fromEmail: item.from?.emailAddress?.address, fromName: item.from?.emailAddress?.name, subject: item.subject, receivedAt: item.receivedDateTime, snippet: item.bodyPreview, body: stripHtml(item.body?.content || item.bodyPreview || '') })); } const q = encodeURIComponent(`after:${Math.floor((Date.now() - Number(rangeDays) * 86400000) / 1000)}`); const page = await request(`https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${q}&maxResults=100`, { headers: { authorization: `Bearer ${token.access_token}` } }); const rows = []; for (const item of page.messages || []) { const full = await request(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${item.id}?format=full`, { headers: { authorization: `Bearer ${token.access_token}` } }); const headers = Object.fromEntries((full.payload?.headers || []).map((header) => [header.name.toLowerCase(), header.value])); rows.push({ providerMessageId: headers['message-id'] || item.id, threadId: full.threadId, fromEmail: headers.from, subject: headers.subject, receivedAt: headers.date || new Date().toISOString(), snippet: full.snippet, body: decodeGmailBody(full.payload) }); } return rows; }
function decodeGmailBody(payload) { if (!payload || payload.filename || (payload.mimeType && !/^text\/(plain|html)/i.test(payload.mimeType) && payload.parts?.length === 0)) return ''; if (payload.body?.data && (!payload.mimeType || /^text\//i.test(payload.mimeType))) return stripHtml(Buffer.from(payload.body.data.replace(/-/g, '+').replace(/_/g, '/'), 'base64').toString('utf8')); const parts = (payload.parts || []).filter((part) => !part.filename && (!part.mimeType || /^text\//i.test(part.mimeType) || part.parts?.length)); for (const part of parts) { const value = decodeGmailBody(part); if (value) return value; } return ''; }
function stripHtml(value) { return String(value || '').replace(/<style[\s\S]*?<\/style>|<script[\s\S]*?<\/script>/gi, ' ').replace(/<[^>]+>/g, ' ').replace(/&nbsp;/gi, ' ').replace(/\s+/g, ' ').trim(); }
module.exports = { createMailService, PROVIDERS, encryptCredential, decryptCredential, fetchOAuthMessages };
